name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

resources:
- repo: self
  clean: all
  fetchDepth: 1

trigger:
  branches:
   include:
    - main/*
  paths:
   include:
    - backend/*

variables:
  - group: devopslab


pool:
  name: devopslab
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@4
  displayName: 'Replace variables'
  inputs:
    rootDirectory: backend
    targetFiles: |
     deployment.yaml
     app.js
    tokenPattern: custom

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'gcp-registry'
    repository: 'the-tree-beneath-329315/devops/backend'
    command: build
    Dockerfile: backend/Dockerfile
    tags: '$(Build.SourceBranchName)'

- task: Anchore@0
  inputs:
    image: 'gcr.io/the-tree-beneath-329315/devops/backend:$(Build.SourceBranchName)'
    dockerfile: 'backend/Dockerfile'
    failBuild: false
#    customPolicyPath: '.anchore/policy.json'

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'gcp-registry'
    repository: 'the-tree-beneath-329315/devops/backend'
    tags: '$(Build.SourceBranchName)'
    command: push

- task: Kubernetes@1
  displayName: 'kubectl apply'
  inputs:
    kubernetesServiceEndpoint: k8s
    command: apply
    useConfigurationFile: true
    configuration: backend/deployment.yaml
