name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: retodevops
      type: github
      ref: refs/heads/main
      name: retodevops

trigger:
  branches:
   include:
    - main/*
  paths:
   include:
    - backend/*

#variables:
#  - group: variable


pool:
  name: devopslab
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@4
  displayName: 'Replace variables'
  inputs:
    rootDirectory: backend
    targetFiles: |
     deployment.yaml
     app.js
    tokenPattern: custom

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'gcp-registry'
    repository: 'the-tree-beneath-329315/devops/backend'
    command: build
    Dockerfile: backend/Dockerfile

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'gcp-registry'
    repository: 'the-tree-beneath-329315/devops/backend'
    command: push

- task: KubernetesManifest@0
  displayName: deploy
  inputs:
    kubernetesServiceConnection: k8s
    manifests: backend/deployment.yaml

- task: Kubernetes@1
  displayName: 'kubectl apply'
  inputs:
    kubernetesServiceEndpoint: k8s
    command: apply
    useConfigurationFile: true
    configuration: backend/deployment.yaml
