---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "backend"
  namespace: "default"
  labels:
    app: "backend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
      - name: "backend-1"
        image: "#{containerimage}#"
        ports:
        - containerPort: 3000
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "frontend-hpa-fdxb"
  namespace: "default"
  labels:
    app: "backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "backend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
