---
#apiVersion: "apps/v1"
#kind: "Deployment"
#metadata:
#  name: "backend"
#  namespace: "default"
#  labels:
#    app: "backend"
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: "backend"
#  template:
#    metadata:
#      labels:
#        app: "backend"
#    spec:
#      containers:
#      - name: "backend-1"
#        image: "#{containerimage}#"
#        ports:
#        - containerPort: 3000


apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "backendchart.fullname" . }}
  namespace: "default"
  labels:
    {{- include "backendchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backendchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backendchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "backend-hpa-fdxb"
  namespace: "default"
  labels:
    app: "backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "backend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "backendchart.fullname" . }}
  labels:
    {{- include "backendchart" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: backend
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "backendchart.selectorLabels" . | nindent 4 }}

#apiVersion: v1
#kind: Service
#metadata:
#  name: backend
#spec:
# selector:
#  app: backend
# ports:
# - protocol: TCP
#   port: 3000
#   targetPort: 3000


# apiVersion: v1
#kind: Service
#metadata:
#  name: backend
#  labels:
#    name: backend
#spec:
#  type: LoadBalancer
#  ports:
#    - name: backend
#      port: 3000
#      targetPort: 3000
#  selector:
#    app: backend
